name: Unusuality
version: 2.0
api-version: 1.21
bootstrapper: su.mrhantur.UnusualityBootstrapper
main: su.mrhantur.Unusuality
description: Unusuality plugin with bootstrapper
author: MrHantur
permissions:
  unusuality.chance:
    description: "/uc"
    default: true
  unusuality.chance.admin:
    default: op
  unusuality.giveunusual:
    default: op