name: Unusuality
version: 1.0-SNAPSHOT
api-version: 1.21
bootstrapper: su.mrhantur.UnusualityBootstrapper
main: su.mrhantur.Unusuality
description: Unusuality plugin with bootstrapper
author: MrHantur

dependencies:
  bootstrap: {}
  server: {}
